---
title: "PAF"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Unit check that PAF calculations are ok

```{r}
# Type 2 diabetes moderate-severe
## PAF 14,5% = 0.145
P=0.068 # 6.8 
RR=1.63
PAF = (P*(RR -1)) / (P*(RR-1)+1)
PAF
## Miksi ei tasmaa??
```




## Use Italy data from article and calculate PAF

```{r}
# paf_or(OR, prevalence, osa_table()$rate[osa_table()$gender == "Both" & osa_table()$var == "Moderate-Severe"])
paf_or <- function(OR, PD, PE){
  PE_ = 100 - PE
  VALUE1 = (PD * (1 - OR) + PE_ + OR * PE + sqrt( (PD * (1 - OR) + PE_ + OR * PE )^2 - 4 * PE_ * (1 - OR) *PD )) / (2 * PE_ * (1 - OR))
  VALUE2 = (PD * (1 - OR) + PE_ + OR * PE - sqrt( (PD * (1 - OR) + PE_ + OR * PE )^2 - 4 * PE_ * (1 - OR) *PD )) / (2 * PE_ * (1 - OR))
  VALUE <- ifelse(VALUE1 < 100 & VALUE1 > 0, VALUE1, VALUE2)
  PAF = 1 - ((100 * VALUE) / PD)
  return(PAF)
}
```

```{r}
library(tidyverse)
d <- readxl::read_xlsx("/Users/japmiett/projects/sleep22/data/osa_tables.xlsx", sheet = "tbl2")

d %>% 
  mutate(
    ## PAF formula from TODO ADD SOURCE. Is it specific for Armeni?
    PAFRR = ifelse(!is.na(RR), (prevalence_base_italy * (RR - 1) / (prevalence_base_italy * (RR - 1) + 1)), NA), 
    PAFRR2 = ifelse(!is.na(RR), (100*prevalence_base_italy * (RR - 1) / (100*prevalence_base_italy * (RR - 1) + 1)), NA), 
    # TODO here PAF calculation for OR
    PAFOR = ifelse(!is.na(OR), paf_or(OR, prevalence_base_italy, 0.27), NA)
  ) %>% 
    select(cause_id, Conditon, prevalence_base_italy, OR, RR, PAF, PAFRR, PAFRR2, PAFOR) -> d_tmp
```


